[package]
name = "game_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shakmaty = "0.26"
quickphf_codegen = "*"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
